# @name login
POST {{host}}/api/v1/user/login
Content-Type: application/json

{
  "email": "miiro@qq.com",
  "password": "233233"
}

> {%
    client.log(response.body.data.token);
    
    client.global.set("auth_token", response.body.data.token); 
%}

###
# @name add video
POST {{host}}/api/v1/video
Authorization: {{auth_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="title"

hanami
--WebAppBoundary
Content-Disposition: form-data; name="age"

29
--WebAppBoundary
Content-Disposition: form-data; name="file"
Content-Type: image/jpeg

#C:\Users\HANAMI\Desktop\QQ图片20221121101438.jpg

--WebAppBoundary--

###

# @name get video by id
GET {{host}}/api/v1/video/1?name=hanami
Authorization: {{auth_token}}

###
# @name 获取收藏 
GET {{host}}/api/v1/user/collection/video
Authorization: {{auth_token}}

###
# @name 新增收藏 
POST {{host}}/api/v1/user/collection/video
Authorization: {{auth_token}}
Content-Type: application/json

{
  "vid": 5
}

###
# @name 取消收藏
DELETE {{host}}/api/v1/user/collection/video/1
Authorization: {{auth_token}}